-- 1.
CREATE VIEW DWREANPAROXES AS 
SELECT eName,ePrice
FROM EXTRAS
WHERE ePrice IS NULL;

SELECT * FROM DWREANPAROXES;

-- 2.
CREATE VIEW PELATES AS
SELECT CUSTOMER.cAFM,CUSTOMER.cAT,CUSTOMER.cLastName,CUSTOMER.cFirstName,CUSTOMER.cRegDate,PHONE.cPhone 
FROM CUSTOMER,PHONE
WHERE CUSTOMER.cAFM=PHONE.cAFM;

SELECT * FROM PELATES;

-- 3.
CREATE VIEW XWRISPHONE AS
SELECT CUSTOMER.CAFM,CUSTOMER.CAT,CUSTOMER.CLASTNAME,CUSTOMER.CFIRSTNAME,CUSTOMER.CREGDATE,
PHONE.CPHONE FROM CUSTOMER,PHONE
WHERE CUSTOMER.CAFM=PHONE.CAFM(+) AND CPHONE IS NULL;

SELECT * FROM XWRISPHONE;

-- 4.
CREATE VIEW PAST_5_DAYS AS
SELECT cFirstName,cLastName
FROM CUSTOMER
WHERE cRegDate >= sysdate-5
ORDER BY cRegDate DESC;

SELECT * FROM PAST_5_DAYS;

-- 5.
CREATE VIEW CUSTOMER_CURRENT_RENT AS
SELECT CUSTOMER.CAFM,CUSTOMER.CLASTNAME,CUSTOMER.CFIRSTNAME,
RENTING.VPLATENUMBER,RENTING.OUTDATE,RENTING.INDATE FROM CUSTOMER,RENTING
WHERE CUSTOMER.CAFM=RENTING.CAFM(+);

SELECT * FROM CUSTOMER_CURRENT_RENT;

--6.
CREATE SEQUENCE RentSeq INCREMENT BY 10 START WITH 1000;

--7.
ALTER TABLE RENTING ADD RENT_ID CHAR(5);

--8.
UPDATE RENTING SET RENT_ID = RentSeq.NEXTVAL;

--9.
ALTER TABLE RENTING ADD CONSTRAINT rentcheck CHECK (RENT_ID BETWEEN 1000 AND 2000);

-- 10.
CREATE INDEX CUSTOMER_idx ON CUSTOMER (cFirstName,cLastName);

SELECT * FROM CUSTOMER WHERE cLastName = 'ANDREAS';