INSERT INTO DEPARTMENT(DEPTNO, NAME) VALUES(10,'PWLHSEIS');
INSERT INTO DEPARTMENT(DEPTNO, NAME) VALUES(20,'MHX/SH');
INSERT INTO DEPARTMENT(DEPTNO, NAME) VALUES(30,'LOGISTHRIO');
INSERT INTO DEPARTMENT(DEPTNO, NAME) VALUES(40,'DIOIKHTHRIO');

INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(10,'ATHINA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(20,'ATHINA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(20,'KABALA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(20,'LARISA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(30,'ATHINA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(40,'ATHINA');
INSERT INTO DLOCATION(DEPTNO, LOCATION) VALUES(40,'THESSALONIKH');

INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(100,'NIKOS','NIKOY','M','YAKINTHOU 2',800.35,100.00,'PROGRAMMER',10);
INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(101,'ANDREAS','ANDREOY','M','KOLOKOTRWNH 12',800.35,NULL,'PROGRAMMER',10);
INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(102,'IWANNHS','IWANNOY','M','NABARINOY 23',800.35,1200,'PROGRAMMER',10);
INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(201,'GEWRGIA','GEWRGIOY','F','ANAKSAGORA 40',800.35,1200,'PROGRAMMER',10);
INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(202,'ANTWNIA','ANTWNIOY','F','ANAKSAGORA 40',800.35,1200,'PROGRAMMER',10);

INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(101,'Dimitris','M',TO_DATE('01/03/1996','DD/MM/YYYY'),1); 
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(101,'Dimitra','F',TO_DATE('01/03/1996','DD/MM/YYYY'),1); 
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(101,'Antrianna','F',TO_DATE('13/05/1980','DD/MM/YYYY'),2);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(101,'Nikh','F',TO_DATE('13/07/1981','DD/MM/YYYY'),2);  

INSERT INTO PROJECT(PROJNO, NAME, LOCATION, DEPTNO) VALUES(10001,'MHX/SH NOSOKOMEIWN','MAROUSI',20);
INSERT INTO PROJECT(PROJNO, NAME, LOCATION, DEPTNO) VALUES(10002,'MHX/SH DHM. SXOLEIWN','KABALA',20);
INSERT INTO PROJECT(PROJNO, NAME, LOCATION, DEPTNO) VALUES(10003,'MHX/SH TEE','KABALA',20);

INSERT INTO WORKSON(IDNUM, PROJNO, HOURS) VALUES(101,10002,200);
INSERT INTO WORKSON(IDNUM, PROJNO, HOURS) VALUES(101,10003,200);
INSERT INTO WORKSON(IDNUM, PROJNO, HOURS) VALUES(100,10001,200);

INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(5254,'IWANNHS','ARGYROPOULOS','M','PAPAMIXAHL 32',950,1350,'SOFTWARE ENGINEER',20);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(5254,'Iwannhs','M',TO_DATE('22/01/1990','DD/MM/YYYY'),2);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(5254,'Chris','M',TO_DATE('05/09/2010','DD/MM/YYYY'),1);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(5254,'Despoina','F',TO_DATE('28/12/2013','DD/MM/YYYY'),1);

INSERT INTO EMPLOYEE(IDNUM, FNAME, LNAME, SEX, ADDRESS, SALARY, BONUS, JOB, DEPTNO) VALUES(5545,'THANASIS','ATHANASIOY','M','MPOUMPOULINAS 27',1000,1500,'DB ADMIN',40);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(5545,'Thanasis','M',TO_DATE('17/04/1991','DD/MM/YYYY'),2);
INSERT INTO DEPENDENT(IDNUM, NAME, SEX, BDATE, RELATIONSHIP) VALUES(5545,'Maria','F',TO_DATE('12/12/2012','DD/MM/YYYY'),1);